server:
  port: 8080
  servlet:
    session.timeout: 300

logging:
  level:
    org.springframework.web: debug
    cn.zifangsky.quickmodules: debug
    org.apache.shiro: debug
  file: logs/quick-modules-example.log


spring:
  #Hikari
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quick-modules?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#mybatis
mybatis:
  type-aliases-package: cn.zifangsky.quickmodules.example.mapper
  mapper-locations: classpath:mapper/*.xml

#是否开启Springfox Swagger
swagger.enabled: true